# Generated by Django 4.1.3 on 2022-11-27 02:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appseguridadAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proceso')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo', models.TextField(blank=True, null=True, verbose_name='Riesgo')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turnos',
            field=models.CharField(choices=[('N', 'Noche'), ('T', 'Tarde'), ('M', 'Mañana')], default='M', max_length=20, verbose_name='Turnos'),
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='fecha')),
                ('Area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appseguridadAPI.area')),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('Area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appseguridadAPI.area')),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peligro', models.TextField(blank=True, null=True, verbose_name='Peligro')),
                ('medida_preventiva', models.TextField(blank=True, null=True, verbose_name='medida')),
                ('puntaje', models.IntegerField(blank=True, default=0, null=True, verbose_name='puntaje')),
                ('puntajeFinal', models.IntegerField(blank=True, default=0, null=True, verbose_name='puntaje')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appseguridadAPI.procesos')),
                ('riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appseguridadAPI.riesgo')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appseguridadAPI.sesiones')),
            ],
        ),
    ]
