# Generated by Django 4.1.3 on 2022-11-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseguridadAPI', '0003_alter_peligro_sesion_remove_sesiones_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCreacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido')),
                ('jefe', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jefe')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turnos',
            field=models.CharField(choices=[('T', 'Tarde'), ('N', 'Noche'), ('M', 'Mañana')], default='M', max_length=20, verbose_name='Turnos'),
        ),
    ]
