# Generated by Django 4.1.3 on 2022-12-01 04:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appseguridadAPI', '0005_reporte_usuariojefe_alter_usuario_turnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='turnos',
            field=models.CharField(choices=[('T', 'Tarde'), ('N', 'Noche'), ('M', 'Mañana')], default='M', max_length=20, verbose_name='Turnos'),
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='fecha')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appseguridadAPI.sesiones', verbose_name='session')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
